/*  ka_crosswalk_patterns.js — shared render functions for the five topic-page variants.

    Exposes window.KA_CROSSWALK with:
      loadCrosswalk()        -> Promise<{rows, outcomes, families}>
      renderHeatmap(data, mountEl)
      renderFaceted(data, mountEl)
      renderMultiview(data, mountEl)
      renderBidirectional(data, mountEl)
      renderProgressiveDisclosure(data, mountEl, opts?)

    Each render function takes:
      data       = {rows, outcomes, families}   // returned by loadCrosswalk()
      mountEl    = HTMLElement into which the pattern's DOM is written
      opts       = {showHelpButton: bool}        // pattern 5 only, for modal help

    The functions are extracted verbatim from docs/crosswalk_gui_mockups.html
    so the five standalone topic-page variants and the mockups page stay in
    sync. Keep this file alongside the topic-page HTMLs (same origin) so the
    crosswalk JSON fetch resolves.

    Data source (relative): data/ka_payloads/topic_crosswalk.json
    Generated by scripts/build_ka_adapter_payloads.py (Codex).
*/
(function(){
  const CROSSWALK_URL = "data/ka_payloads/topic_crosswalk.json";

  async function loadCrosswalk() {
    const r = await fetch(CROSSWALK_URL);
    if (!r.ok) throw new Error(`crosswalk fetch failed: ${r.status} ${r.statusText}`);
    const data = await r.json();
    return {
      rows:     data.rows          || [],
      outcomes: data.outcome_index || [],
      families: data.iv_root_index || [],
    };
  }

  // ── Pattern 1: Heatmap ─────────────────────────────────────────
  function renderHeatmap({rows, outcomes, families}, mount) {
    const cells = new Map();
    let maxCount = 0;
    for (const r of rows) {
      const k = `${r.iv_root}||${r.outcome_term_id || r.dv_focus || "?"}`;
      const e = cells.get(k) || {count: 0, rows: []};
      e.count += r.paper_count || 0;
      e.rows.push(r);
      cells.set(k, e);
      if (e.count > maxCount) maxCount = e.count;
    }
    const colorFor = (c) => {
      if (!c) return "#FBFBFB";
      const t = Math.log(1 + c) / Math.log(1 + maxCount);
      return `rgb(${Math.round(245-t*215)},${Math.round(245-t*180)},${Math.round(240-t*180)})`;
    };
    let html = '<table class="heatmap"><thead><tr><th></th>';
    for (const o of outcomes) {
      html += `<th class="outcome-col" title="${escapeHtml(o.outcome_label)}">${escapeHtml(o.outcome_label)}</th>`;
    }
    html += "</tr></thead><tbody>";
    for (const f of families) {
      html += `<tr><th>${escapeHtml(f.iv_root_label || f.iv_root)}</th>`;
      for (const o of outcomes) {
        const cell = cells.get(`${f.iv_root}||${o.outcome_term_id || "?"}`);
        const c = cell ? cell.count : 0;
        html += `<td class="${c ? "" : "empty"}" style="background:${colorFor(c)};"
                     title="${escapeHtml(f.iv_root_label)} × ${escapeHtml(o.outcome_label)}: ${c} paper${c===1?"":"s"}">${c || ""}</td>`;
      }
      html += "</tr>";
    }
    html += "</tbody></table>";
    mount.innerHTML = html;
  }

  // ── Pattern 2: Faceted filter ──────────────────────────────────
  function renderFaceted(data, mount) {
    const {rows, outcomes, families} = data;
    const state = {outcome: null, family: null};
    mount.innerHTML = `
      <div class="facet-layout">
        <div class="facet-panel" id="__ka_facet_panel"></div>
        <div class="facet-results" id="__ka_facet_results"></div>
      </div>`;
    const panel = mount.querySelector("#__ka_facet_panel");
    const resultsEl = mount.querySelector("#__ka_facet_results");

    const redraw = () => {
      const oFiltered = state.family
        ? rows.filter(r => r.iv_root === state.family).map(r => r.outcome_term_id || r.dv_focus)
        : null;
      const oSet = oFiltered ? new Set(oFiltered) : null;
      let oHtml = `<div class="facet-group"><div class="label">Outcome${
        state.outcome ? ` · <span class="clear-link" data-clear="outcome">clear</span>` : ""}</div>`;
      for (const o of outcomes) {
        const dimmed = oSet && !oSet.has(o.outcome_term_id);
        const selected = state.outcome === o.outcome_term_id;
        oHtml += `<span class="chip ${selected?"selected":""}" data-facet="outcome" data-id="${escapeAttr(o.outcome_term_id)}" ${dimmed?'style="opacity:.3"':""}>${escapeHtml(o.outcome_label)} <span class="count">${o.paper_count}</span></span>`;
      }
      oHtml += "</div>";

      const fFiltered = state.outcome
        ? rows.filter(r => (r.outcome_term_id || r.dv_focus) === state.outcome).map(r => r.iv_root)
        : null;
      const fSet = fFiltered ? new Set(fFiltered) : null;
      let fHtml = `<div class="facet-group"><div class="label">Architectural family${
        state.family ? ` · <span class="clear-link" data-clear="family">clear</span>` : ""}</div>`;
      for (const f of families) {
        const dimmed = fSet && !fSet.has(f.iv_root);
        const selected = state.family === f.iv_root;
        fHtml += `<span class="chip ${selected?"selected":""}" data-facet="family" data-id="${escapeAttr(f.iv_root)}" ${dimmed?'style="opacity:.3"':""}>${escapeHtml(f.iv_root_label || f.iv_root)} <span class="count">${f.paper_count}</span></span>`;
      }
      fHtml += "</div>";
      panel.innerHTML = oHtml + fHtml;

      let results = rows.slice();
      if (state.outcome) results = results.filter(r => (r.outcome_term_id || r.dv_focus) === state.outcome);
      if (state.family)  results = results.filter(r => r.iv_root === state.family);
      results.sort((a,b)=>(b.paper_count||0)-(a.paper_count||0));

      let rHtml = `<h4>Defended bundles <span style="font-weight:400;color:#6B6B6B">(${results.length})</span></h4>`;
      if (!results.length) {
        rHtml += '<div style="color:#6B6B6B;font-size:0.86rem">No defended bundles match this filter combination. This cell is in the gap set.</div>';
      } else {
        for (const r of results.slice(0, 30)) {
          const pill = r.evidence_status === "defended" ? "status-pill" :
                       r.evidence_status === "mixed" ? "status-pill mixed" : "status-pill unresolved";
          rHtml += `<div class="bundle-row">
            <div class="bundle-title">${escapeHtml(r.topic_label || r.topic_id)}
              <span class="${pill}">${escapeHtml(r.evidence_status || "working")}</span></div>
            <div class="bundle-meta">${escapeHtml(r.outcome_label)} × ${escapeHtml(r.iv_root_label || r.iv_root)} ·
              <b>${r.paper_count || 0}</b> paper${r.paper_count===1?"":"s"}
              ${r.defended_paper_count ? `· <b>${r.defended_paper_count}</b> defended` : ""}</div>
          </div>`;
        }
        if (results.length > 30) rHtml += `<div class="bundle-row" style="color:#6B6B6B;text-align:center">… and ${results.length-30} more</div>`;
      }
      resultsEl.innerHTML = rHtml;
    };

    panel.addEventListener("click", e => {
      const clearEl = e.target.closest("[data-clear]");
      if (clearEl) { state[clearEl.dataset.clear] = null; return redraw(); }
      const chip = e.target.closest("[data-facet]");
      if (!chip) return;
      const k = chip.dataset.facet;
      state[k] = state[k] === chip.dataset.id ? null : chip.dataset.id;
      redraw();
    });
    redraw();
  }

  // ── Pattern 3: Coordinated multi-view ──────────────────────────
  function renderMultiview(data, mount) {
    const {rows, outcomes, families} = data;
    const state = {outcome: null, family: null};
    mount.innerHTML = `
      <div class="multi-view">
        <div class="mv-panel" id="__ka_mv_outcomes"></div>
        <div class="mv-panel" id="__ka_mv_families"></div>
        <div class="mv-panel" id="__ka_mv_bundles"></div>
      </div>`;
    const oEl = mount.querySelector("#__ka_mv_outcomes");
    const fEl = mount.querySelector("#__ka_mv_families");
    const bEl = mount.querySelector("#__ka_mv_bundles");

    const redraw = () => {
      const oAllowed = state.family
        ? new Set(rows.filter(r => r.iv_root === state.family).map(r => r.outcome_term_id || r.dv_focus))
        : null;
      let h = "<h4>Outcomes</h4>";
      for (const o of outcomes) {
        const dimmed = oAllowed && !oAllowed.has(o.outcome_term_id);
        const selected = state.outcome === o.outcome_term_id;
        h += `<div class="mv-item ${selected?"selected":""} ${dimmed?"dimmed":""}" data-k="outcome" data-id="${escapeAttr(o.outcome_term_id)}">
          <div>${escapeHtml(o.outcome_label)}</div>
          <div class="mv-sub">${o.paper_count} papers · ${o.topic_ids ? o.topic_ids.length : 0} bundles</div>
        </div>`;
      }
      oEl.innerHTML = h;

      const fAllowed = state.outcome
        ? new Set(rows.filter(r => (r.outcome_term_id || r.dv_focus) === state.outcome).map(r => r.iv_root))
        : null;
      h = "<h4>Architectural families</h4>";
      for (const f of families) {
        const dimmed = fAllowed && !fAllowed.has(f.iv_root);
        const selected = state.family === f.iv_root;
        h += `<div class="mv-item ${selected?"selected":""} ${dimmed?"dimmed":""}" data-k="family" data-id="${escapeAttr(f.iv_root)}">
          <div>${escapeHtml(f.iv_root_label || f.iv_root)}</div>
          <div class="mv-sub">${f.paper_count} papers · ${f.topic_ids ? f.topic_ids.length : 0} bundles</div>
        </div>`;
      }
      fEl.innerHTML = h;

      let bundles = rows.slice();
      if (state.outcome) bundles = bundles.filter(r => (r.outcome_term_id || r.dv_focus) === state.outcome);
      if (state.family)  bundles = bundles.filter(r => r.iv_root === state.family);
      bundles.sort((a,b)=>(b.paper_count||0)-(a.paper_count||0));
      h = `<h4>Defended bundles (${bundles.length})</h4>`;
      if (!bundles.length) {
        h += '<div style="color:#6B6B6B;font-size:0.85rem;padding:8px">No bundles for this selection.</div>';
      } else {
        for (const b of bundles.slice(0, 50)) {
          h += `<div class="mv-item">
            <div>${escapeHtml(b.topic_label || b.topic_id)}</div>
            <div class="mv-sub">${escapeHtml(b.outcome_label)} × ${escapeHtml(b.iv_root_label || b.iv_root)} · ${b.paper_count||0} papers</div>
          </div>`;
        }
        if (bundles.length > 50) h += `<div class="mv-item" style="color:#8A9A96">… ${bundles.length-50} more</div>`;
      }
      bEl.innerHTML = h;
    };

    mount.addEventListener("click", e => {
      const item = e.target.closest("[data-k]");
      if (!item) return;
      const k = item.dataset.k;
      state[k] = state[k] === item.dataset.id ? null : item.dataset.id;
      redraw();
    });
    redraw();
  }

  // ── Pattern 4: Bidirectional lookup ────────────────────────────
  function renderBidirectional(data, mount) {
    const {rows, outcomes, families} = data;
    mount.innerHTML = `
      <div class="bidir">
        <div class="bidir-side">
          <h4>Start with an outcome</h4>
          <select id="__ka_bd_o"><option value="">Choose an outcome…</option></select>
          <div class="bidir-output" id="__ka_bd_o_out">
            <span style="color:#8A9A96;font-size:0.85rem">Pick an outcome to see matching architectural families.</span>
          </div>
        </div>
        <div class="bidir-side">
          <h4>Start with an architectural family</h4>
          <select id="__ka_bd_f"><option value="">Choose a family…</option></select>
          <div class="bidir-output" id="__ka_bd_f_out">
            <span style="color:#8A9A96;font-size:0.85rem">Pick a family to see matching outcomes.</span>
          </div>
        </div>
      </div>`;
    const oSel = mount.querySelector("#__ka_bd_o");
    const fSel = mount.querySelector("#__ka_bd_f");
    for (const o of outcomes) { const opt = document.createElement("option"); opt.value = o.outcome_term_id; opt.textContent = `${o.outcome_label} (${o.paper_count})`; oSel.appendChild(opt); }
    for (const f of families) { const opt = document.createElement("option"); opt.value = f.iv_root; opt.textContent = `${f.iv_root_label||f.iv_root} (${f.paper_count})`; fSel.appendChild(opt); }
    oSel.addEventListener("change", e => {
      const oid = e.target.value; if (!oid) return;
      const matching = rows.filter(r => (r.outcome_term_id||r.dv_focus) === oid);
      const byFam = {};
      for (const r of matching) {
        byFam[r.iv_root] = byFam[r.iv_root] || {label: r.iv_root_label, n:0, bundles:[]};
        byFam[r.iv_root].n += r.paper_count || 0;
        byFam[r.iv_root].bundles.push(r.topic_label || r.topic_id);
      }
      const sorted = Object.entries(byFam).sort((a,b)=>b[1].n-a[1].n);
      mount.querySelector("#__ka_bd_o_out").innerHTML = sorted.map(([root,info]) =>
        `<div class="item"><strong>${escapeHtml(info.label||root)}</strong><span class="n">${info.n} papers · ${info.bundles.length} bundle${info.bundles.length===1?"":"s"}</span></div>`
      ).join("") || '<div style="color:#6B6B6B">No matches.</div>';
    });
    fSel.addEventListener("change", e => {
      const fid = e.target.value; if (!fid) return;
      const matching = rows.filter(r => r.iv_root === fid);
      const byO = {};
      for (const r of matching) {
        const k = r.outcome_term_id || r.dv_focus || "?";
        byO[k] = byO[k] || {label: r.outcome_label, n:0, bundles:[]};
        byO[k].n += r.paper_count || 0;
        byO[k].bundles.push(r.topic_label || r.topic_id);
      }
      const sorted = Object.entries(byO).sort((a,b)=>b[1].n-a[1].n);
      mount.querySelector("#__ka_bd_f_out").innerHTML = sorted.map(([oid,info]) =>
        `<div class="item"><strong>${escapeHtml(info.label||oid)}</strong><span class="n">${info.n} papers · ${info.bundles.length} bundle${info.bundles.length===1?"":"s"}</span></div>`
      ).join("") || '<div style="color:#6B6B6B">No matches.</div>';
    });
  }

  // ── Pattern 5: Progressive disclosure ──────────────────────────
  function renderProgressiveDisclosure(data, mount) {
    const {rows, outcomes, families} = data;
    const state = {stage: 0, entry: null, outcome: null, family: null};

    const groupFor = (oid) => {
      const k = (oid || "").toLowerCase();
      if (k.startsWith("cog.")) return "Cognitive outcomes";
      if (k.startsWith("affect.")) return "Affective / emotional outcomes";
      if (k === "physio" || k === "neural" || k === "health") return "Physiological & health outcomes";
      if (k.startsWith("behav.")) return "Behavioural outcomes";
      return "Other / cross-cutting";
    };

    const redraw = () => {
      let html = "";
      if (state.stage > 0) {
        html += '<div class="pd-crumb">';
        if (state.outcome) {
          const o = outcomes.find(x => x.outcome_term_id === state.outcome);
          html += `<span class="crumb-item"><span class="crumb-label">OUTCOME</span>${escapeHtml(o ? o.outcome_label : state.outcome)}</span>`;
        }
        if (state.family) {
          if (state.outcome) html += '<span class="crumb-sep">›</span>';
          const f = families.find(x => x.iv_root === state.family);
          html += `<span class="crumb-item"><span class="crumb-label">ARCHITECTURE</span>${escapeHtml(f ? (f.iv_root_label || f.iv_root) : state.family)}</span>`;
        }
        html += `<span class="pd-reset" data-act="reset">start over</span>`;
        html += "</div>";
      }

      if (state.stage === 0) {
        html += `<div class="pd-stage">
          <h4>Where would you like to start?</h4>
          <div class="pd-sub">Pick whichever axis feels more natural. You can change your mind at any step.</div>
          <div class="pd-entry-row">
            <button class="pd-entry-btn" data-act="entry" data-val="outcome">
              <span class="label">A specific outcome I care about</span>
              <span class="sub">Stress, attention, wellbeing, sleep, restoration, comfort, preference, navigation…</span>
            </button>
            <button class="pd-entry-btn" data-act="entry" data-val="family">
              <span class="label">An architectural feature I'm curious about</span>
              <span class="sub">Luminous, acoustic, spatial form, natural elements, material, thermal…</span>
            </button>
            <button class="pd-entry-btn" data-act="entry" data-val="overview">
              <span class="label">Show me the full landscape</span>
              <span class="sub">Jumps to the full faceted view on the Full Facets variant page.</span>
            </button>
          </div>
        </div>`;
        mount.innerHTML = html;
        return;
      }

      if (state.entry === "outcome" && !state.outcome) {
        html += `<div class="pd-stage">
          <h4>Which outcome?</h4>
          <div class="pd-sub">Outcomes are grouped by category. Click a category to expand its options.</div>`;
        const groups = {};
        for (const o of outcomes) (groups[groupFor(o.outcome_term_id)] = groups[groupFor(o.outcome_term_id)] || []).push(o);
        for (const [gName, gOs] of Object.entries(groups)) {
          const total = gOs.reduce((s,o)=>s+(o.paper_count||0),0);
          const slug = gName.replace(/[^a-z]/gi,"");
          html += `<div class="pd-group">
            <div class="pd-group-head" data-act="toggleGroup" data-slug="${slug}" id="pdhead-${slug}">
              <span><span class="pd-caret">▸</span><span class="pd-name">${escapeHtml(gName)}</span></span>
              <span class="pd-count">${gOs.length} option${gOs.length===1?"":"s"} · ${total} papers</span>
            </div>
            <div class="pd-group-body" id="pdbody-${slug}">`;
          for (const o of gOs) html += `<span class="chip" data-act="pick" data-k="outcome" data-id="${escapeAttr(o.outcome_term_id)}">${escapeHtml(o.outcome_label)} <span class="count">${o.paper_count}</span></span>`;
          html += `</div></div>`;
        }
        html += `<div class="pd-escape">Prefer everything at once? <a data-act="entry" data-val="overview">Show all facets</a></div></div>`;
        mount.innerHTML = html;
        return;
      }

      if (state.entry === "family" && !state.family) {
        html += `<div class="pd-stage">
          <h4>Which architectural feature?</h4>
          <div class="pd-sub">Nine families. Pick the one closest to your interest.</div>`;
        for (const f of families) html += `<span class="chip" data-act="pick" data-k="family" data-id="${escapeAttr(f.iv_root)}">${escapeHtml(f.iv_root_label||f.iv_root)} <span class="count">${f.paper_count} papers · ${f.topic_ids ? f.topic_ids.length : 0} bundles</span></span>`;
        html += `<div class="pd-escape">Prefer everything at once? <a data-act="entry" data-val="overview">Show all facets</a></div></div>`;
        mount.innerHTML = html;
        return;
      }

      let matchingRows;
      if (state.outcome && !state.family) {
        matchingRows = rows.filter(r => (r.outcome_term_id || r.dv_focus) === state.outcome);
        const mfIds = [...new Set(matchingRows.map(r => r.iv_root))];
        const mf = families.filter(f => mfIds.includes(f.iv_root));
        html += `<div class="pd-stage">
          <h4>Now: which architectural feature?</h4>
          <div class="pd-sub">Only families with defended bundles for this outcome are shown.</div>`;
        for (const f of mf) {
          const n = matchingRows.filter(r => r.iv_root === f.iv_root).length;
          html += `<span class="chip" data-act="pick" data-k="family" data-id="${escapeAttr(f.iv_root)}">${escapeHtml(f.iv_root_label||f.iv_root)} <span class="count">${n} bundle${n===1?"":"s"}</span></span>`;
        }
        if (!mf.length) html += '<div class="pd-sub">No defended bundles for this outcome yet. Try another.</div>';
        html += `<div style="margin-top:10px;font-size:0.82rem;color:#6B6B6B">Or <a style="color:#2A7868;cursor:pointer" data-act="showAll">show all ${matchingRows.length} bundles for this outcome</a>.</div></div>`;
        mount.innerHTML = html;
        return;
      }
      if (state.family && !state.outcome) {
        matchingRows = rows.filter(r => r.iv_root === state.family);
        const moIds = [...new Set(matchingRows.map(r => r.outcome_term_id || r.dv_focus))];
        const mo = outcomes.filter(o => moIds.includes(o.outcome_term_id));
        html += `<div class="pd-stage">
          <h4>Now: which outcome?</h4>
          <div class="pd-sub">Only outcomes with defended bundles for this architectural family are shown.</div>`;
        for (const o of mo) {
          const n = matchingRows.filter(r => (r.outcome_term_id||r.dv_focus) === o.outcome_term_id).length;
          html += `<span class="chip" data-act="pick" data-k="outcome" data-id="${escapeAttr(o.outcome_term_id)}">${escapeHtml(o.outcome_label)} <span class="count">${n} bundle${n===1?"":"s"}</span></span>`;
        }
        if (!mo.length) html += '<div class="pd-sub">No defended bundles for this family yet. Try another.</div>';
        html += `<div style="margin-top:10px;font-size:0.82rem;color:#6B6B6B">Or <a style="color:#2A7868;cursor:pointer" data-act="showAll">show all ${matchingRows.length} bundles for this family</a>.</div></div>`;
        mount.innerHTML = html;
        return;
      }

      matchingRows = rows.slice();
      if (state.outcome) matchingRows = matchingRows.filter(r => (r.outcome_term_id || r.dv_focus) === state.outcome);
      if (state.family)  matchingRows = matchingRows.filter(r => r.iv_root === state.family);
      matchingRows.sort((a,b)=>(b.paper_count||0)-(a.paper_count||0));
      html += `<div class="pd-stage"><h4>Defended bundles (${matchingRows.length})</h4>`;
      if (!matchingRows.length) {
        html += '<div class="pd-sub">No bundles match this combination. Either this cell is in the evidence gap, or the crosswalk has not yet defended a bundle here. Try adjusting one of the facets above.</div>';
      } else {
        for (const r of matchingRows.slice(0,30)) {
          const pill = r.evidence_status === "defended" ? "status-pill" : r.evidence_status === "mixed" ? "status-pill mixed" : "status-pill unresolved";
          html += `<div class="bundle-row">
            <div class="bundle-title">${escapeHtml(r.topic_label || r.topic_id)} <span class="${pill}">${escapeHtml(r.evidence_status || "working")}</span></div>
            <div class="bundle-meta">${escapeHtml(r.outcome_label)} × ${escapeHtml(r.iv_root_label || r.iv_root)} · <b>${r.paper_count||0}</b> paper${r.paper_count===1?"":"s"} ${r.defended_paper_count ? `· <b>${r.defended_paper_count}</b> defended` : ""}</div>
          </div>`;
        }
        if (matchingRows.length > 30) html += `<div class="bundle-row" style="color:#6B6B6B;text-align:center">… and ${matchingRows.length-30} more</div>`;
      }
      html += "</div>";
      mount.innerHTML = html;
    };

    mount.addEventListener("click", e => {
      const t = e.target.closest("[data-act]");
      if (!t) return;
      const act = t.dataset.act;
      if (act === "entry") {
        if (t.dataset.val === "overview") { window.location = "ka_topic_full_facets_view.html"; return; }
        state.entry = t.dataset.val; state.stage = 1; return redraw();
      }
      if (act === "pick") {
        state[t.dataset.k] = t.dataset.id;
        state.stage = (state.outcome && state.family) ? 3 : 2;
        return redraw();
      }
      if (act === "showAll") { state.stage = 3; return redraw(); }
      if (act === "reset") {
        state.stage = 0; state.entry = null; state.outcome = null; state.family = null;
        return redraw();
      }
      if (act === "toggleGroup") {
        const slug = t.dataset.slug;
        document.getElementById("pdhead-"+slug)?.classList.toggle("expanded");
        document.getElementById("pdbody-"+slug)?.classList.toggle("open");
      }
    });

    redraw();
  }

  // ── Small escapes ──────────────────────────────────────────────
  function escapeHtml(s) {
    return String(s == null ? "" : s).replace(/[&<>"']/g, c => ({
      "&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"
    }[c]));
  }
  function escapeAttr(s) { return escapeHtml(s).replace(/"/g,"&quot;"); }

  window.KA_CROSSWALK = {
    loadCrosswalk,
    renderHeatmap,
    renderFaceted,
    renderMultiview,
    renderBidirectional,
    renderProgressiveDisclosure,
  };
})();
